name: flutter_webview_plugin
description: Plugin that allow Flutter to communicate with a native Webview.
authors:
  - Hadrien Lejard <hadrien.lejard@gmail.com>
  - Toufik Zitouni <toufiksapps@gmail.com>
  - Pedia <kpedia@163.com>
  - Simon Lightfoot <simon@devangels.london>
  - Rafal Wachol <gorudonu@gmail.com>
  - Bhagat Singh <bhagatsingh9084@gmail.com>

homepage: https://github.com/Bhagat8533/flutter_webview_plugin
version: 0.1.0
maintainer: Bhagat Singh

environment:
  sdk: ">=2.16.1 <3.0.0"

flutter:
  plugin:
    androidPackage: com.flutter_webview_plugin
    pluginClass: FlutterWebviewPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter